// GENERATED by scripts/write-build-info.mjs — do not edit.
// Lets the running page state which build it is, so a stale deploy is visible
// instead of being argued about.
export const BUILD_SHA = "e75f50b";
export const BUILD_AT = "2026-09-26T18:20:36.881Z";
