// GENERATED by scripts/write-build-info.mjs — do not edit.
// Lets the running page state which build it is, so a stale deploy is visible
// instead of being argued about.
export const BUILD_SHA = "6fe96fd";
export const BUILD_AT = "2026-09-26T17:45:14.626Z";
