// GENERATED by scripts/write-build-info.mjs — do not edit.
// Lets the running page state which build it is, so a stale deploy is visible
// instead of being argued about.
export const BUILD_SHA = "39a1ae4";
export const BUILD_AT = "2026-09-26T18:18:27.300Z";
